### ISSUE TITLE
Property getting proven even if signal does not exist

### ISSUE THREAD

**Issue by ShashankVM** [diffblue/hw-cbmc#659]
I had written a cover property:
`COVER_ERROR_INJECTED: cover property  (@(posedge clk) disable iff (reset) (tx_channel_in != tx_channel_out));`

I remvoed tx_channel_in and tx_channel_out from the file but the property still got proven.

**Comment by kroening** [comment]
Please try with the current main -- ebmc is now stricter with implicitly declared wires.

**Comment by ShashankVM** [comment]
Thanks, @kroening this fixed it.
